version: "3"
services:
  app:
    build: .
    image: abushka/delivery_bot-master-app
    volumes:
      - .:/usr/src/greed/
      - ./config:/usr/src/greed/config
    depends_on:
      - db
    restart: always
    command: python -OO core.py
    env_file:
      - ./.env
  db:
    image: postgres:12
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: