version: "3"
services:
  app:
    build: .
    depends_on:
      - db
  db:
    image: postgres:12
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: